<?php

return [
    'categories' => [
        [
            'key' => 'password-remover',
            'name' => 'Password Remover',
            'summary' => 'Unlock and recover access to your own protected files.',
            'tools' => [
                [
                    'slug' => 'excel-vba-password-remover',
                    'name' => 'Excel VBA Password Remover',
                    'status' => 'Live',
                    'tagline' => 'Recover access to your own Excel VBA project files.',
                    'description' => 'Upload your workbook and submit a reset request for VBA protection removal when you own the file and have recovery authorization.',
                    'input_type' => 'file',
                    'accept' => '.xls,.xlsx,.xlsm',
                    'validation_rules' => ['file', 'mimes:xls,xlsx,xlsm', 'max:51200'],
                    'button_label' => 'Remove VBA Password',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Recover inherited macro templates.',
                        'Maintain blocked internal automation sheets.',
                        'Restore access to legacy workbook logic.',
                    ],
                ],
                [
                    'slug' => 'excel-sheet-password-remover',
                    'name' => 'Excel Sheet Password Remover',
                    'status' => 'Live',
                    'tagline' => 'Remove worksheet-level protection from owned spreadsheets.',
                    'description' => 'Upload an Excel file to request sheet protection reset and regain editing permissions for locked worksheet content.',
                    'input_type' => 'file',
                    'accept' => '.xls,.xlsx,.xlsm',
                    'validation_rules' => ['file', 'mimes:xls,xlsx,xlsm', 'max:51200'],
                    'button_label' => 'Remove Sheet Password',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Recover editing access to protected worksheets.',
                        'Fix locked formulas and hidden cells.',
                        'Enable team collaboration on restricted files.',
                    ],
                ],
                [
                    'slug' => 'pdf-password-remover',
                    'name' => 'PDF Password Remover',
                    'status' => 'Live',
                    'tagline' => 'Remove open-password restrictions from your PDF files.',
                    'description' => 'Upload protected PDF files and request password removal for files you legally own or have explicit permission to recover.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Remove PDF Password',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Open archived reports without blockers.',
                        'Recover readable copies for team review.',
                        'Enable print and edit flows on secured PDFs.',
                    ],
                ],
            ],
        ],
        [
            'key' => 'converter',
            'name' => 'Converter',
            'summary' => 'Convert common document and image formats quickly.',
            'tools' => [
                [
                    'slug' => 'combine-pdf-files',
                    'name' => 'Combine PDF Files',
                    'status' => 'Live',
                    'tagline' => 'Merge multiple PDF documents into one output file.',
                    'description' => 'Upload PDF files and combine them into one consolidated document for sharing and archiving.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Combine PDF Files',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Bundle several reports into one file.',
                        'Merge invoices and supporting attachments.',
                        'Prepare one upload-ready PDF package.',
                    ],
                ],
                [
                    'slug' => 'convert-pdf-to-grayscale',
                    'name' => 'Convert PDF to Grayscale',
                    'status' => 'Live',
                    'tagline' => 'Reduce color usage by converting PDF pages to grayscale.',
                    'description' => 'Upload a PDF and convert all pages to grayscale for printing optimization and smaller outputs.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to Grayscale',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Save ink for office print jobs.',
                        'Standardize monochrome document output.',
                        'Prepare print-ready grayscale documents.',
                    ],
                ],
                [
                    'slug' => 'dicom-to-pdf',
                    'name' => 'DICOM to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert DICOM medical imaging files to PDF.',
                    'description' => 'Upload DICOM files and convert selected frames to PDF for secure sharing and record workflows.',
                    'input_type' => 'file',
                    'accept' => '.dcm,.dicom',
                    'validation_rules' => ['file', 'max:51200'],
                    'button_label' => 'Convert DICOM to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Share selected diagnostics in PDF format.',
                        'Generate readable attachments for referrals.',
                        'Create printable snapshots from DICOM files.',
                    ],
                ],
                [
                    'slug' => 'dxf-to-pdf',
                    'name' => 'DXF to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert DXF engineering drawings to PDF.',
                    'description' => 'Upload DXF files and produce PDF copies for review, approvals, and client sharing.',
                    'input_type' => 'file',
                    'accept' => '.dxf',
                    'validation_rules' => ['file', 'max:51200'],
                    'button_label' => 'Convert DXF to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Share CAD drawings with non-CAD users.',
                        'Create printable design review documents.',
                        'Package technical diagrams for proposals.',
                    ],
                ],
                [
                    'slug' => 'excel-to-pdf',
                    'name' => 'Excel to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert Excel sheets to PDF format.',
                    'description' => 'Upload spreadsheet files and export them as fixed-layout PDFs for approvals and reporting.',
                    'input_type' => 'file',
                    'accept' => '.xls,.xlsx,.xlsm',
                    'validation_rules' => ['file', 'mimes:xls,xlsx,xlsm', 'max:51200'],
                    'button_label' => 'Convert Excel to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Share non-editable spreadsheet reports.',
                        'Prepare monthly statement attachments.',
                        'Preserve layouts across devices.',
                    ],
                ],
                [
                    'slug' => 'html-to-pdf',
                    'name' => 'HTML to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert HTML pages into portable PDFs.',
                    'description' => 'Upload HTML files and generate PDF snapshots suitable for archiving and distribution.',
                    'input_type' => 'file',
                    'accept' => '.html,.htm',
                    'validation_rules' => ['file', 'mimes:html,htm', 'max:51200'],
                    'button_label' => 'Convert HTML to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Archive web pages as static documents.',
                        'Share HTML-based drafts as PDFs.',
                        'Store printable versions of templates.',
                    ],
                ],
                [
                    'slug' => 'image-to-excel',
                    'name' => 'Image to Excel',
                    'status' => 'Live',
                    'tagline' => 'Extract tabular data from images into Excel files.',
                    'description' => 'Upload scanned tables or screenshots and convert detected data to an Excel spreadsheet.',
                    'input_type' => 'file',
                    'accept' => '.jpg,.jpeg,.png,.webp,.tif,.tiff',
                    'validation_rules' => ['file', 'mimes:jpg,jpeg,png,webp,tif,tiff', 'max:51200'],
                    'button_label' => 'Convert Image to Excel',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Digitize printed tables quickly.',
                        'Capture invoice line items from images.',
                        'Move scan-based data into spreadsheets.',
                    ],
                ],
                [
                    'slug' => 'jpg-to-pdf',
                    'name' => 'JPG to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert JPG images into PDF documents.',
                    'description' => 'Upload JPG or JPEG images and convert them into shareable PDF format.',
                    'input_type' => 'file',
                    'accept' => '.jpg,.jpeg',
                    'validation_rules' => ['file', 'mimes:jpg,jpeg', 'max:51200'],
                    'button_label' => 'Convert JPG to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Package photographed pages as PDF.',
                        'Send JPG scans in one standard format.',
                        'Prepare image-based submissions.',
                    ],
                ],
                [
                    'slug' => 'pdf-converter',
                    'name' => 'PDF Converter',
                    'status' => 'Live',
                    'tagline' => 'Run general PDF conversion workflows.',
                    'description' => 'Upload PDF files for broad conversion workflows where output type is selected during processing.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Start PDF Conversion',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Prepare PDF files for alternate formats.',
                        'Centralize standard PDF conversion jobs.',
                        'Apply common pre-processing on PDF assets.',
                    ],
                ],
                [
                    'slug' => 'pdf-to-excel',
                    'name' => 'PDF to Excel',
                    'status' => 'Live',
                    'tagline' => 'Convert PDF tables into editable Excel spreadsheets.',
                    'description' => 'Upload PDF files and convert extracted table content into editable Excel output.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to Excel',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Extract financial table data from PDFs.',
                        'Reuse tabular report content in Excel.',
                        'Convert scanned statements for analysis.',
                    ],
                ],
                [
                    'slug' => 'pdf-to-jpg',
                    'name' => 'PDF to JPG',
                    'status' => 'Live',
                    'tagline' => 'Convert PDF pages into JPG images.',
                    'description' => 'Upload a PDF and export pages as JPG image files for sharing and publishing.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to JPG',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Create image previews from PDF pages.',
                        'Use PDF pages in slide decks and posts.',
                        'Export document pages for quick sharing.',
                    ],
                ],
                [
                    'slug' => 'pdf-to-pdfa-converter',
                    'name' => 'PDF to PDF/A Converter',
                    'status' => 'Live',
                    'tagline' => 'Convert PDF files into archival PDF/A format.',
                    'description' => 'Upload PDF documents and convert them to standards-compliant PDF/A for long-term retention.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to PDF/A',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Meet records retention requirements.',
                        'Archive compliance-sensitive documents.',
                        'Preserve long-term document readability.',
                    ],
                ],
                [
                    'slug' => 'pdf-to-png',
                    'name' => 'PDF to PNG',
                    'status' => 'Live',
                    'tagline' => 'Convert PDF pages into PNG images.',
                    'description' => 'Upload PDF files and convert pages to PNG for transparent or lossless image workflows.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to PNG',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Generate high-quality image exports.',
                        'Create web-ready graphics from PDFs.',
                        'Extract clean diagrams from documents.',
                    ],
                ],
                [
                    'slug' => 'pdf-to-powerpoint',
                    'name' => 'PDF to Powerpoint',
                    'status' => 'Live',
                    'tagline' => 'Convert PDF slides into editable presentation files.',
                    'description' => 'Upload PDF decks and convert to PowerPoint format for editing and reuse.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to Powerpoint',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Edit legacy slide decks shared as PDF.',
                        'Repurpose PDF presentations quickly.',
                        'Recover editable content for training.',
                    ],
                ],
                [
                    'slug' => 'pdf-to-text',
                    'name' => 'PDF to Text',
                    'status' => 'Live',
                    'tagline' => 'Extract plain text content from PDFs.',
                    'description' => 'Upload PDF files and extract readable text output for editing, indexing, or analysis.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to Text',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Extract report content for reuse.',
                        'Prepare text for documentation systems.',
                        'Analyze PDF text with external tools.',
                    ],
                ],
                [
                    'slug' => 'pdf-to-tiff',
                    'name' => 'PDF to TIFF',
                    'status' => 'Live',
                    'tagline' => 'Convert PDF pages into TIFF images.',
                    'description' => 'Upload PDF files and export pages as TIFF images for archival and print workflows.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to TIFF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Export to archival TIFF imaging.',
                        'Prepare high-resolution scan outputs.',
                        'Support TIFF-based print systems.',
                    ],
                ],
                [
                    'slug' => 'tiff-to-pdf-converter',
                    'name' => 'TIFF to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert TIFF image files into PDF documents.',
                    'description' => 'Upload TIFF scans and convert them into PDF format for easier sharing, archiving, and printing.',
                    'input_type' => 'file',
                    'accept' => '.tif,.tiff',
                    'validation_rules' => ['file', 'mimes:tif,tiff', 'max:51200'],
                    'button_label' => 'Convert TIFF to PDF',
                    'processing_mode' => 'instant',
                    'processor' => 'tiff_to_pdf',
                    'use_cases' => [
                        'Submit scanned paperwork in PDF format.',
                        'Merge scanned pages into portable documents.',
                        'Standardize scan outputs for sharing.',
                    ],
                ],
                [
                    'slug' => 'word-to-pdf-converter',
                    'name' => 'Word to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert Word files into fixed-layout PDFs.',
                    'description' => 'Upload DOC and DOCX files and convert them to PDF for approvals, print, and secure sharing.',
                    'input_type' => 'file',
                    'accept' => '.doc,.docx',
                    'validation_rules' => ['file', 'mimes:doc,docx', 'max:51200'],
                    'button_label' => 'Convert Word to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Export contracts to non-editable format.',
                        'Share proposals with preserved layout.',
                        'Prepare print-ready office files.',
                    ],
                ],
                [
                    'slug' => 'pdf-to-word-converter',
                    'name' => 'PDF to Word',
                    'status' => 'Live',
                    'tagline' => 'Convert PDF files into editable Word documents.',
                    'description' => 'Upload PDF files and convert them into DOCX format so content can be edited and updated easily.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to Word',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Reuse archived PDF content in reports.',
                        'Fix text in documents originally shared as PDF.',
                        'Extract editable content for reformatting.',
                    ],
                ],
                [
                    'slug' => 'png-to-pdf',
                    'name' => 'PNG to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert PNG images into PDF documents.',
                    'description' => 'Upload PNG images and package them as PDF files for sharing and printing.',
                    'input_type' => 'file',
                    'accept' => '.png',
                    'validation_rules' => ['file', 'mimes:png', 'max:51200'],
                    'button_label' => 'Convert PNG to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Turn PNG exports into printable files.',
                        'Share design snapshots as PDF.',
                        'Bundle transparent assets as documents.',
                    ],
                ],
                [
                    'slug' => 'ppt-to-pdf',
                    'name' => 'PPT to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert PowerPoint presentations to PDF.',
                    'description' => 'Upload PPT or PPTX files and convert them to PDF while preserving layout.',
                    'input_type' => 'file',
                    'accept' => '.ppt,.pptx',
                    'validation_rules' => ['file', 'mimes:ppt,pptx', 'max:51200'],
                    'button_label' => 'Convert PPT to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Share slides in non-editable format.',
                        'Create print-ready board packs.',
                        'Preserve deck layout consistency.',
                    ],
                ],
                [
                    'slug' => 'scan-to-pdf',
                    'name' => 'Scan to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert scanned images into PDF documents.',
                    'description' => 'Upload scans from phone or scanner and convert to clean PDF output.',
                    'input_type' => 'file',
                    'accept' => '.jpg,.jpeg,.png,.webp,.tif,.tiff',
                    'validation_rules' => ['file', 'mimes:jpg,jpeg,png,webp,tif,tiff', 'max:51200'],
                    'button_label' => 'Convert Scan to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Digitize paper documents quickly.',
                        'Create searchable office scan batches.',
                        'Package receipts and forms for sharing.',
                    ],
                ],
                [
                    'slug' => 'svg-to-pdf',
                    'name' => 'SVG to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert SVG vector assets into PDF format.',
                    'description' => 'Upload SVG graphics and convert them into portable PDF documents.',
                    'input_type' => 'file',
                    'accept' => '.svg',
                    'validation_rules' => ['file', 'mimes:svg', 'max:51200'],
                    'button_label' => 'Convert SVG to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Deliver vector diagrams in PDF format.',
                        'Prepare print-ready logo and icon assets.',
                        'Share design exports with non-design tools.',
                    ],
                ],
                [
                    'slug' => 'txt-to-pdf',
                    'name' => 'TXT to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert plain text files into PDF documents.',
                    'description' => 'Upload TXT files and convert plain text notes into standardized PDF output.',
                    'input_type' => 'file',
                    'accept' => '.txt',
                    'validation_rules' => ['file', 'mimes:txt', 'max:51200'],
                    'button_label' => 'Convert TXT to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Package simple text records as PDF.',
                        'Prepare logs for document sharing.',
                        'Create printable copies of note files.',
                    ],
                ],
                [
                    'slug' => 'image-to-pdf-converter',
                    'name' => 'Image to PDF',
                    'status' => 'Live',
                    'tagline' => 'Convert image files into shareable PDF documents.',
                    'description' => 'Upload JPG, PNG, WEBP, or TIFF files and convert them into PDF format in one workflow.',
                    'input_type' => 'file',
                    'accept' => '.jpg,.jpeg,.png,.webp,.tif,.tiff',
                    'validation_rules' => ['file', 'mimes:jpg,jpeg,png,webp,tif,tiff', 'max:51200'],
                    'button_label' => 'Convert Image to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Archive photographed files as PDF.',
                        'Prepare images for legal/business submissions.',
                        'Share image batches as one document.',
                    ],
                ],
            ],
        ],
        [
            'key' => 'generators',
            'name' => 'Generators',
            'summary' => 'Generate utility output for links, signatures, and IDs.',
            'tools' => [
                [
                    'slug' => 'qr-code-generator',
                    'name' => 'QR Code Generator',
                    'status' => 'Live',
                    'tagline' => 'Generate a QR link from plain text or URL input.',
                    'description' => 'Paste a URL or plain text and generate a ready QR code endpoint for quick scanning and distribution.',
                    'input_type' => 'text',
                    'button_label' => 'Generate QR Link',
                    'processing_mode' => 'instant',
                    'processor' => 'qr_link',
                    'use_cases' => [
                        'Share website links with mobile users.',
                        'Generate QR links for posters and flyers.',
                        'Create quick access links for events.',
                    ],
                ],
                [
                    'slug' => 'hash-generator',
                    'name' => 'Hash Generator',
                    'status' => 'Live',
                    'tagline' => 'Generate SHA-256 signatures from input text.',
                    'description' => 'Paste any string and generate a SHA-256 hash for verification, integrity checks, and developer workflows.',
                    'input_type' => 'text',
                    'button_label' => 'Generate Hash',
                    'processing_mode' => 'instant',
                    'processor' => 'hash_sha256',
                    'use_cases' => [
                        'Verify payload integrity.',
                        'Create consistent signatures for content.',
                        'Generate deterministic test values.',
                    ],
                ],
                [
                    'slug' => 'uuid-generator',
                    'name' => 'UUID Generator',
                    'status' => 'Live',
                    'tagline' => 'Generate unique UUID v4 identifiers.',
                    'description' => 'Generate UUID values instantly for records, references, API entities, and system identifiers.',
                    'input_type' => 'text',
                    'button_label' => 'Generate UUID',
                    'processing_mode' => 'instant',
                    'processor' => 'uuid_v4',
                    'use_cases' => [
                        'Create unique IDs for database records.',
                        'Assign references to documents and jobs.',
                        'Generate identifiers for integration payloads.',
                    ],
                ],
                [
                    'slug' => 'json-formatter',
                    'name' => 'JSON Formatter',
                    'status' => 'Live',
                    'tagline' => 'Format raw JSON into readable structure.',
                    'description' => 'Paste JSON input and format it with clean indentation for API debugging and documentation.',
                    'input_type' => 'text',
                    'button_label' => 'Format JSON',
                    'processing_mode' => 'instant',
                    'processor' => 'json_formatter',
                    'use_cases' => [
                        'Inspect API responses quickly.',
                        'Clean payloads before sharing.',
                        'Validate JSON structure before use.',
                    ],
                ],
                [
                    'slug' => 'base64-encoder',
                    'name' => 'Base64 Encoder',
                    'status' => 'Live',
                    'tagline' => 'Encode text payloads to Base64.',
                    'description' => 'Convert plain text into Base64 output for transport, integrations, and config usage.',
                    'input_type' => 'text',
                    'button_label' => 'Encode Text',
                    'processing_mode' => 'instant',
                    'processor' => 'base64_encode',
                    'use_cases' => [
                        'Prepare values for APIs.',
                        'Generate encoded strings quickly.',
                        'Standardize payload encoding for testing.',
                    ],
                ],
            ],
        ],
        [
            'key' => 'downloaders',
            'name' => 'Downloaders',
            'summary' => 'Prepare and process downloads from supported media platforms.',
            'tools' => [
                [
                    'slug' => 'youtube-video-downloader',
                    'name' => 'YouTube Video Downloader',
                    'status' => 'Live',
                    'tagline' => 'Paste a YouTube URL and auto-generate quality options for video and MP3.',
                    'description' => 'Paste a valid YouTube link and automatically load available video resolutions (1080p/720p/360p and more) plus MP3 options with direct download buttons.',
                    'input_type' => 'text',
                    'button_label' => 'Load Formats',
                    'processing_mode' => 'instant',
                    'processor' => 'youtube_downloader',
                    'use_cases' => [
                        'Generate direct download buttons per video quality.',
                        'Download MP3 audio versions from the same URL.',
                        'Normalize watch, shorts, and embed links automatically.',
                    ],
                ],
            ],
        ],
    ],
];
