<?php

return [
    'categories' => [
        [
            'key' => 'document-conversion',
            'name' => 'Document Conversion',
            'summary' => 'Convert and restructure office documents for everyday workflows.',
            'tools' => [
                [
                    'slug' => 'pdf-to-word-converter',
                    'name' => 'PDF to Word Converter',
                    'status' => 'Live',
                    'tagline' => 'Turn PDF documents into editable Word files.',
                    'description' => 'Upload PDF files and convert them into editable DOCX format for easy revision and collaboration.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to Word',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Edit reports that were only shared as PDF.',
                        'Reuse content from archived proposals.',
                        'Extract text for faster document updates.',
                    ],
                ],
                [
                    'slug' => 'word-to-pdf-converter',
                    'name' => 'Word to PDF Converter',
                    'status' => 'Live',
                    'tagline' => 'Convert DOC and DOCX files into consistent PDFs.',
                    'description' => 'Upload Word files and export them to PDF for sharing, approvals, and print-ready delivery.',
                    'input_type' => 'file',
                    'accept' => '.doc,.docx',
                    'validation_rules' => ['file', 'mimes:doc,docx', 'max:51200'],
                    'button_label' => 'Convert Word to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Share finalized contracts in a fixed format.',
                        'Send proposals with stable layout across devices.',
                        'Prepare print-safe copies of office documents.',
                    ],
                ],
                [
                    'slug' => 'pdf-merge-tool',
                    'name' => 'PDF Merge Tool',
                    'status' => 'Live',
                    'tagline' => 'Combine multiple PDF documents into one file.',
                    'description' => 'Merge project files, scans, and reports into a single PDF package for easier sharing.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Merge PDF Files',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Compile tender attachments into one document.',
                        'Bundle signed pages into one final report.',
                        'Create submission packs for clients.',
                    ],
                ],
                [
                    'slug' => 'pdf-split-tool',
                    'name' => 'PDF Split Tool',
                    'status' => 'Live',
                    'tagline' => 'Extract selected pages from large PDF files.',
                    'description' => 'Split large PDFs into smaller documents by page ranges so teams can share only what is needed.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Split PDF Document',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Extract invoice sections from large scans.',
                        'Share chapter-specific files with teams.',
                        'Prepare selected pages for client review.',
                    ],
                ],
            ],
        ],
        [
            'key' => 'spreadsheet-utilities',
            'name' => 'Spreadsheet Utilities',
            'summary' => 'Tools focused on Excel, VBA, and tabular data handling.',
            'tools' => [
                [
                    'slug' => 'excel-vba-password-remover',
                    'name' => 'Excel VBA Password Remover',
                    'status' => 'Live',
                    'tagline' => 'Recover access to your own VBA projects in Excel files.',
                    'description' => 'Upload your workbook to remove or reset VBA project protection when you have legitimate ownership access.',
                    'input_type' => 'file',
                    'accept' => '.xls,.xlsx,.xlsm',
                    'validation_rules' => ['file', 'mimes:xls,xlsx,xlsm', 'max:51200'],
                    'button_label' => 'Unlock VBA Project',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Regain access to inherited macro workbooks.',
                        'Resume maintenance of legacy automation files.',
                        'Fix blocked VBA modules in internal templates.',
                    ],
                ],
                [
                    'slug' => 'excel-to-csv-converter',
                    'name' => 'Excel to CSV Converter',
                    'status' => 'Live',
                    'tagline' => 'Convert Excel worksheets to CSV format quickly.',
                    'description' => 'Export spreadsheet data into CSV for imports, integrations, analytics, and automation pipelines.',
                    'input_type' => 'file',
                    'accept' => '.xls,.xlsx',
                    'validation_rules' => ['file', 'mimes:xls,xlsx', 'max:51200'],
                    'button_label' => 'Convert Excel to CSV',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Prepare data for software imports.',
                        'Move tabular content into scripts and databases.',
                        'Normalize worksheets for reporting tools.',
                    ],
                ],
                [
                    'slug' => 'csv-to-excel-converter',
                    'name' => 'CSV to Excel Converter',
                    'status' => 'Live',
                    'tagline' => 'Transform CSV datasets into Excel workbooks.',
                    'description' => 'Upload CSV files and convert them into Excel format for formatting, formulas, and easier business review.',
                    'input_type' => 'file',
                    'accept' => '.csv,.txt',
                    'validation_rules' => ['file', 'mimes:csv,txt', 'max:51200'],
                    'button_label' => 'Convert CSV to Excel',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Prepare imported data for office teams.',
                        'Add formulas and pivots to flat datasets.',
                        'Create shareable workbook versions of reports.',
                    ],
                ],
            ],
        ],
        [
            'key' => 'image-and-ocr',
            'name' => 'Image and OCR Tools',
            'summary' => 'Convert image formats and extract text from scanned assets.',
            'tools' => [
                [
                    'slug' => 'image-to-pdf-converter',
                    'name' => 'Image to PDF Converter',
                    'status' => 'Live',
                    'tagline' => 'Combine JPG, PNG, and WEBP images into PDF.',
                    'description' => 'Upload image files and package them as a PDF document suitable for sharing, printing, or submission.',
                    'input_type' => 'file',
                    'accept' => '.jpg,.jpeg,.png,.webp',
                    'validation_rules' => ['file', 'mimes:jpg,jpeg,png,webp', 'max:51200'],
                    'button_label' => 'Convert Image to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Submit scanned IDs and forms as PDF.',
                        'Archive photographed paperwork into one file.',
                        'Prepare visual evidence packs for teams.',
                    ],
                ],
                [
                    'slug' => 'image-text-extractor-ocr',
                    'name' => 'Image Text Extractor (OCR)',
                    'status' => 'Live',
                    'tagline' => 'Extract editable text from images and scanned pages.',
                    'description' => 'Run OCR on screenshots and scanned documents to recover text for editing, searching, and translation.',
                    'input_type' => 'file',
                    'accept' => '.jpg,.jpeg,.png,.webp,.pdf',
                    'validation_rules' => ['file', 'mimes:jpg,jpeg,png,webp,pdf', 'max:51200'],
                    'button_label' => 'Extract Text with OCR',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Digitize printed documents into editable text.',
                        'Extract content from screenshots quickly.',
                        'Enable searchability for scanned archives.',
                    ],
                ],
            ],
        ],
        [
            'key' => 'data-and-dev',
            'name' => 'Data and Dev Utilities',
            'summary' => 'Quick developer-friendly tools with instant on-page processing.',
            'tools' => [
                [
                    'slug' => 'json-formatter',
                    'name' => 'JSON Formatter',
                    'status' => 'Live',
                    'tagline' => 'Validate and pretty-print JSON payloads.',
                    'description' => 'Paste raw JSON and format it into clean, readable output for debugging, APIs, and documentation.',
                    'input_type' => 'text',
                    'button_label' => 'Format JSON',
                    'processing_mode' => 'instant',
                    'processor' => 'json_formatter',
                    'use_cases' => [
                        'Inspect API responses during development.',
                        'Clean payloads before sharing with teams.',
                        'Validate syntax quickly before deployment.',
                    ],
                ],
                [
                    'slug' => 'base64-encoder',
                    'name' => 'Base64 Encoder',
                    'status' => 'Live',
                    'tagline' => 'Encode plain text into Base64 format.',
                    'description' => 'Paste text and convert it to Base64 output for integrations, payload handling, and secure transport workflows.',
                    'input_type' => 'text',
                    'button_label' => 'Encode Text',
                    'processing_mode' => 'instant',
                    'processor' => 'base64_encode',
                    'use_cases' => [
                        'Prepare encoded strings for APIs.',
                        'Generate Base64 snippets for config values.',
                        'Test encoding logic in integration flows.',
                    ],
                ],
                [
                    'slug' => 'base64-decoder',
                    'name' => 'Base64 Decoder',
                    'status' => 'Live',
                    'tagline' => 'Decode Base64 payloads into readable text.',
                    'description' => 'Paste Base64 data and decode it to recover readable content for debugging and analysis.',
                    'input_type' => 'text',
                    'button_label' => 'Decode Base64',
                    'processing_mode' => 'instant',
                    'processor' => 'base64_decode',
                    'use_cases' => [
                        'Inspect encoded API payloads.',
                        'Recover readable data from logs.',
                        'Verify encoded values during QA.',
                    ],
                ],
            ],
        ],
    ],
];
