<?php

return [
    'categories' => [
        [
            'key' => 'password-remover',
            'name' => 'Password Remover',
            'summary' => 'Unlock and recover access to your own protected files.',
            'tools' => [
                [
                    'slug' => 'excel-vba-password-remover',
                    'name' => 'Excel VBA Password Remover',
                    'status' => 'Live',
                    'tagline' => 'Recover access to your own Excel VBA project files.',
                    'description' => 'Upload your workbook and submit a reset request for VBA protection removal when you own the file and have recovery authorization.',
                    'input_type' => 'file',
                    'accept' => '.xls,.xlsx,.xlsm',
                    'validation_rules' => ['file', 'mimes:xls,xlsx,xlsm', 'max:51200'],
                    'button_label' => 'Remove VBA Password',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Recover inherited macro templates.',
                        'Maintain blocked internal automation sheets.',
                        'Restore access to legacy workbook logic.',
                    ],
                ],
                [
                    'slug' => 'excel-sheet-password-remover',
                    'name' => 'Excel Sheet Password Remover',
                    'status' => 'Live',
                    'tagline' => 'Remove worksheet-level protection from owned spreadsheets.',
                    'description' => 'Upload an Excel file to request sheet protection reset and regain editing permissions for locked worksheet content.',
                    'input_type' => 'file',
                    'accept' => '.xls,.xlsx,.xlsm',
                    'validation_rules' => ['file', 'mimes:xls,xlsx,xlsm', 'max:51200'],
                    'button_label' => 'Remove Sheet Password',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Recover editing access to protected worksheets.',
                        'Fix locked formulas and hidden cells.',
                        'Enable team collaboration on restricted files.',
                    ],
                ],
                [
                    'slug' => 'pdf-password-remover',
                    'name' => 'PDF Password Remover',
                    'status' => 'Live',
                    'tagline' => 'Remove open-password restrictions from your PDF files.',
                    'description' => 'Upload protected PDF files and request password removal for files you legally own or have explicit permission to recover.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Remove PDF Password',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Open archived reports without blockers.',
                        'Recover readable copies for team review.',
                        'Enable print and edit flows on secured PDFs.',
                    ],
                ],
            ],
        ],
        [
            'key' => 'converter',
            'name' => 'Converter',
            'summary' => 'Convert common document and image formats quickly.',
            'tools' => [
                [
                    'slug' => 'tiff-to-pdf-converter',
                    'name' => 'TIFF to PDF Converter',
                    'status' => 'Live',
                    'tagline' => 'Convert TIFF image files into PDF documents.',
                    'description' => 'Upload TIFF scans and convert them into PDF format for easier sharing, archiving, and printing.',
                    'input_type' => 'file',
                    'accept' => '.tif,.tiff',
                    'validation_rules' => ['file', 'mimes:tif,tiff', 'max:51200'],
                    'button_label' => 'Convert TIFF to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Submit scanned paperwork in PDF format.',
                        'Merge scanned pages into portable documents.',
                        'Standardize scan outputs for sharing.',
                    ],
                ],
                [
                    'slug' => 'word-to-pdf-converter',
                    'name' => 'Word to PDF Converter',
                    'status' => 'Live',
                    'tagline' => 'Convert Word files into fixed-layout PDFs.',
                    'description' => 'Upload DOC and DOCX files and convert them to PDF for approvals, print, and secure sharing.',
                    'input_type' => 'file',
                    'accept' => '.doc,.docx',
                    'validation_rules' => ['file', 'mimes:doc,docx', 'max:51200'],
                    'button_label' => 'Convert Word to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Export contracts to non-editable format.',
                        'Share proposals with preserved layout.',
                        'Prepare print-ready office files.',
                    ],
                ],
                [
                    'slug' => 'pdf-to-word-converter',
                    'name' => 'PDF to Word Converter',
                    'status' => 'Live',
                    'tagline' => 'Convert PDF files into editable Word documents.',
                    'description' => 'Upload PDF files and convert them into DOCX format so content can be edited and updated easily.',
                    'input_type' => 'file',
                    'accept' => '.pdf',
                    'validation_rules' => ['file', 'mimes:pdf', 'max:51200'],
                    'button_label' => 'Convert PDF to Word',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Reuse archived PDF content in reports.',
                        'Fix text in documents originally shared as PDF.',
                        'Extract editable content for reformatting.',
                    ],
                ],
                [
                    'slug' => 'image-to-pdf-converter',
                    'name' => 'Image to PDF Converter',
                    'status' => 'Live',
                    'tagline' => 'Convert image files into shareable PDF documents.',
                    'description' => 'Upload JPG, PNG, WEBP, or TIFF files and convert them into PDF format in one workflow.',
                    'input_type' => 'file',
                    'accept' => '.jpg,.jpeg,.png,.webp,.tif,.tiff',
                    'validation_rules' => ['file', 'mimes:jpg,jpeg,png,webp,tif,tiff', 'max:51200'],
                    'button_label' => 'Convert Image to PDF',
                    'processing_mode' => 'assisted',
                    'use_cases' => [
                        'Archive photographed files as PDF.',
                        'Prepare images for legal/business submissions.',
                        'Share image batches as one document.',
                    ],
                ],
            ],
        ],
        [
            'key' => 'generators',
            'name' => 'Generators',
            'summary' => 'Generate utility output for links, signatures, and IDs.',
            'tools' => [
                [
                    'slug' => 'qr-code-generator',
                    'name' => 'QR Code Generator',
                    'status' => 'Live',
                    'tagline' => 'Generate a QR link from plain text or URL input.',
                    'description' => 'Paste a URL or plain text and generate a ready QR code endpoint for quick scanning and distribution.',
                    'input_type' => 'text',
                    'button_label' => 'Generate QR Link',
                    'processing_mode' => 'instant',
                    'processor' => 'qr_link',
                    'use_cases' => [
                        'Share website links with mobile users.',
                        'Generate QR links for posters and flyers.',
                        'Create quick access links for events.',
                    ],
                ],
                [
                    'slug' => 'hash-generator',
                    'name' => 'Hash Generator',
                    'status' => 'Live',
                    'tagline' => 'Generate SHA-256 signatures from input text.',
                    'description' => 'Paste any string and generate a SHA-256 hash for verification, integrity checks, and developer workflows.',
                    'input_type' => 'text',
                    'button_label' => 'Generate Hash',
                    'processing_mode' => 'instant',
                    'processor' => 'hash_sha256',
                    'use_cases' => [
                        'Verify payload integrity.',
                        'Create consistent signatures for content.',
                        'Generate deterministic test values.',
                    ],
                ],
                [
                    'slug' => 'uuid-generator',
                    'name' => 'UUID Generator',
                    'status' => 'Live',
                    'tagline' => 'Generate unique UUID v4 identifiers.',
                    'description' => 'Generate UUID values instantly for records, references, API entities, and system identifiers.',
                    'input_type' => 'text',
                    'button_label' => 'Generate UUID',
                    'processing_mode' => 'instant',
                    'processor' => 'uuid_v4',
                    'use_cases' => [
                        'Create unique IDs for database records.',
                        'Assign references to documents and jobs.',
                        'Generate identifiers for integration payloads.',
                    ],
                ],
                [
                    'slug' => 'json-formatter',
                    'name' => 'JSON Formatter',
                    'status' => 'Live',
                    'tagline' => 'Format raw JSON into readable structure.',
                    'description' => 'Paste JSON input and format it with clean indentation for API debugging and documentation.',
                    'input_type' => 'text',
                    'button_label' => 'Format JSON',
                    'processing_mode' => 'instant',
                    'processor' => 'json_formatter',
                    'use_cases' => [
                        'Inspect API responses quickly.',
                        'Clean payloads before sharing.',
                        'Validate JSON structure before use.',
                    ],
                ],
                [
                    'slug' => 'base64-encoder',
                    'name' => 'Base64 Encoder',
                    'status' => 'Live',
                    'tagline' => 'Encode text payloads to Base64.',
                    'description' => 'Convert plain text into Base64 output for transport, integrations, and config usage.',
                    'input_type' => 'text',
                    'button_label' => 'Encode Text',
                    'processing_mode' => 'instant',
                    'processor' => 'base64_encode',
                    'use_cases' => [
                        'Prepare values for APIs.',
                        'Generate encoded strings quickly.',
                        'Standardize payload encoding for testing.',
                    ],
                ],
            ],
        ],
    ],
];
