<?php

return [
    'projects' => [
        [
            'slug' => 'oebipas',
            'name' => 'OEBIPAS Electricity Billing Platform',
            'category' => 'Utilities SaaS',
            'status' => 'Live',
            'year' => 2023,
            'short_description' => 'Billing, invoicing, tariff management, and customer usage visibility for electricity operations.',
            'full_description' => 'OEBIPAS is a utility-focused billing platform built to streamline meter ingestion, tariff workflows, customer invoicing, and payment visibility. The system reduces manual billing work while improving transparency for both administrators and end users.',
            'technologies' => ['Laravel', 'Next.js', 'PostgreSQL', 'Tailwind CSS', 'Docker'],
            'features' => [
                'Automated meter data import and validation workflows.',
                'Tariff configuration with flexible billing rules.',
                'Customer account visibility with usage and invoice history.',
                'Administrative reporting for operations and finance teams.',
            ],
            'tags' => ['Billing', 'Utilities', 'Dashboard'],
            'deployment_type' => 'Managed cloud deployment',
            'client_type' => 'Utility operations team',
            'roles' => ['System architecture', 'Full-stack delivery', 'Deployment support'],
            'live_url' => 'https://oebipas.arosoft.io',
            'demo_url' => null,
        ],
        [
            'slug' => 'arofi',
            'name' => 'AROFI Hospitality Booking Platform',
            'category' => 'Hospitality Platform',
            'status' => 'In Development',
            'year' => 2024,
            'short_description' => 'Reservation workflows, room management, guest communications, and hospitality operations in one stack.',
            'full_description' => 'AROFI is a hospitality delivery platform for hotels and booking teams that need a cleaner operational stack. It combines reservation handling, availability management, guest communication, and reporting into a single implementation aligned to hotel workflows.',
            'technologies' => ['Next.js', 'Node.js', 'PostgreSQL', 'Tailwind CSS', 'Docker'],
            'features' => [
                'Booking flow with room availability tracking.',
                'Guest communication support and workflow automation.',
                'Room management, reporting, and internal operator visibility.',
                'Foundation for payments, loyalty, and property-scale expansion.',
            ],
            'tags' => ['Hospitality', 'Reservations', 'Operations'],
            'deployment_type' => 'Containerized private deployment',
            'client_type' => 'Hospitality and accommodation teams',
            'roles' => ['Product design', 'Engineering', 'Operational rollout'],
            'live_url' => null,
            'demo_url' => 'https://demo.arofi.arosoft.io',
        ],
        [
            'slug' => 'kiu-complaint',
            'name' => 'KIU Student Complaint Management System',
            'category' => 'Education System',
            'status' => 'Completed',
            'year' => 2022,
            'short_description' => 'Structured complaint intake, tracking, escalation, and reporting for a university environment.',
            'full_description' => 'This education-focused system supports complaint logging, follow-up handling, and administrative reporting across a student support environment. It gives both operators and leadership better visibility into issue resolution and service quality.',
            'technologies' => ['Laravel', 'React', 'MySQL', 'Tailwind CSS'],
            'features' => [
                'Complaint submission and assignment workflows.',
                'Status visibility for staff and students.',
                'Escalation handling for unresolved issues.',
                'Reporting tools for management review and process improvement.',
            ],
            'tags' => ['Education', 'Complaints', 'Workflow'],
            'deployment_type' => 'Institution-hosted deployment',
            'client_type' => 'University administration',
            'roles' => ['System design', 'Development', 'Implementation support'],
            'live_url' => null,
            'demo_url' => null,
        ],
        [
            'slug' => 'arobill',
            'name' => 'AROBill Invoice and Receipt System',
            'category' => 'Business Tool',
            'status' => 'Live',
            'year' => 2023,
            'short_description' => 'Invoice generation, receipts, quoting, and day-to-day finance support for growing businesses.',
            'full_description' => 'AROBill is designed for businesses that need dependable quoting, invoicing, receipt generation, and finance record support without a bloated workflow. It is structured around speed, clarity, and operational convenience.',
            'technologies' => ['Laravel', 'MySQL', 'Tailwind CSS'],
            'features' => [
                'Invoice, quote, and receipt generation workflows.',
                'Operational clarity for day-to-day finance tasks.',
                'Simple business-ready reporting and client history.',
                'Expandable base for payments and recurring billing.',
            ],
            'tags' => ['Finance', 'Invoices', 'SME'],
            'deployment_type' => 'Cloud-hosted business deployment',
            'client_type' => 'SMEs and internal finance teams',
            'roles' => ['Product design', 'Application build', 'Support'],
            'live_url' => 'https://arobill.arosoft.io',
            'demo_url' => null,
        ],
        [
            'slug' => 'security-monitor',
            'name' => 'Security Monitoring System',
            'category' => 'Monitoring System',
            'status' => 'Completed',
            'year' => 2021,
            'short_description' => 'Live monitoring, alert workflows, and operator visibility for security environments.',
            'full_description' => 'This monitoring system aggregates feeds, operational alerts, and activity records into a single control surface. It supports faster incident awareness and more consistent monitoring workflows for security teams.',
            'technologies' => ['Laravel', 'Node.js', 'WebRTC', 'Tailwind CSS'],
            'features' => [
                'Live feed aggregation for operator visibility.',
                'Alert handling and event tracking support.',
                'Operational dashboards for monitoring teams.',
                'Expandable architecture for higher-volume installations.',
            ],
            'tags' => ['Security', 'Monitoring', 'Operations'],
            'deployment_type' => 'Private infrastructure deployment',
            'client_type' => 'Security operations teams',
            'roles' => ['Systems engineering', 'Deployment', 'Operational support'],
            'live_url' => null,
            'demo_url' => null,
        ],
        [
            'slug' => 'school-management',
            'name' => 'School Management Platform',
            'category' => 'Education System',
            'status' => 'Ready',
            'year' => 2024,
            'short_description' => 'Admissions, fee tracking, records, communication, and reporting for school operations.',
            'full_description' => 'The school management platform is structured around practical administration needs: admissions, student records, fee visibility, parent communication, and reporting. It is intended for institutions that want a tighter operational workflow than spreadsheets and fragmented tools provide.',
            'technologies' => ['Laravel', 'Livewire', 'MySQL', 'Tailwind CSS'],
            'features' => [
                'Student records and admissions workflow handling.',
                'Fee tracking and finance visibility.',
                'School reporting and operational dashboards.',
                'Parent and administrative communication support.',
            ],
            'tags' => ['School', 'Records', 'Administration'],
            'deployment_type' => 'Managed education deployment',
            'client_type' => 'Schools and institutions',
            'roles' => ['Requirements mapping', 'System build', 'Training support'],
            'live_url' => null,
            'demo_url' => null,
        ],
    ],
];
